### ISSUE TITLE
Weird 2 menu settings and error on saving the settings

### ISSUE THREAD

**Issue by Extain** [ruusey/JRelay#1]
![2017-11-12 23_50_23-jrelay](https://user-images.githubusercontent.com/8728733/32714783-450c9c70-c804-11e7-8f0e-82f9d2d3d2fc.png)
![2017-11-12 23_50_54-jrelay](https://user-images.githubusercontent.com/8728733/32714803-59191e96-c804-11e7-8598-f700383d556c.png)

**Comment by ruusey** [comment]
Fixed. Was due to accidentally adding another tab that was meant for a later build and i left some old settings in code that were causing out of bounds errors. If theres 8 settings you cant access the 9th xD. Will upload new dist that contains few other fixes too
